### ISSUE TITLE
How to generalize to other Atari Games?

### ISSUE THREAD

**Issue by chiahsuan156** [devsisters/DQN-tensorflow#20]
Hi i want to run your code to train agent on other games.
Is there any code or hyperparameter that needs to be changed in order to train a nice agent ?

**Comment by carpedm20** [comment]
It highly depends on what the game is. If a game needs a long series of steps to make a decision, you need to increase `history_length`. If the game's state is diverse, you may need to increase `memory_size`. If the game is hard to learn, you need to increase `max_steps`. If the input of the game has higher dimension, you need to change the structure of the network to represent the state more clearly.

**Comment by chiahsuan156** [comment]
Thanks really a lot !
