### ISSUE TITLE
Agent.learning_rate is never set?

### ISSUE THREAD

**Issue by halflings** [devsisters/DQN-tensorflow#28]
I was reading through the code and couldn't figure out where `Agent.learning_rate` is being set. It's used here:

https://github.com/devsisters/DQN-tensorflow/blob/master/dqn/agent.py#L299

But it's only set on the `Config` object, not the `Agent`.

**Comment by carpedm20** [comment]
It's quite weird but it is set [here](https://github.com/devsisters/DQN-tensorflow/blob/master/dqn/base.py#L29)

**Comment by halflings** [comment]
Thanks!
Overall, this implementation is extremely useful to understand DQN, but one thing I don't like is that it's overly complex, with too many abstractions and abusing dynamic features of Python.

Having your config in a dict instead of explicit class attributes only makes the code harder to understand unfortunately.

**Comment by carpedm20** [comment]
Yes, I agree on that. That's why I didn't used it in the more recent RL code https://github.com/carpedm20/deep-rl-tensorflow/blob/master/main.py and I'm still never used those style again.
