### ISSUE TITLE
How much RAM is required for a proper training?

### ISSUE THREAD

**Issue by YigitDemirag** [devsisters/DQN-tensorflow#5]
For on the order of 100M iteration, what was the required amount of RAM in your case? 16GB GPU EC2 instance with 2GB GPU apparently has no enough memory and locks itself down.

**Comment by carpedm20** [comment]
I didn't checked the GPU memory but 16GB should be enough because the model is small. But you need more memory than 2GB for CPU because it needs a huge experience memory. I guess 16GB is enough.
