### ISSUE TITLE
How can you see the results during the run? 

### ISSUE THREAD

**Issue by oronanschel** [devsisters/DQN-tensorflow#7]
or how did you plot all of your figures

**Comment by carpedm20** [comment]
Add ` --display=True` when do `python main` or run `tensorboard --logdir ./logs` to run tensorboard for visualization of training details.

**Comment by bigcat77** [comment]
Is there anyway you could elaborate on how to use tensorboard to get the graphs that you show?

I get it to run in a browser. but I have no idea how to get the plots.

**Comment by douglasrizzo** [comment]
Me too. I point tensorboard to `./logs` and it shows me a very simple graph, but no graphs.
